In [1]:
import numpy as np
import tensorflow as tf

C:\Users\p\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
X_data = [[3, 4]]
Y_data = [[1, 0]]

In [7]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 2])

W = tf.Variable([[1., 2.], [3., 4.]], name = "weight")
b = tf.Variable([1., 2.], name = "bias")

In [8]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis =1))
optimizer =tf.train.GradientDescentOptimizer(learning_rate =0.1)
train = optimizer.minimize(cost)

In [9]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10):
        W_val, b_val, cost_val, hyp_val = sess.run([W, b,cost, hypothesis], feed_dict = {X:X_data, Y:Y_data})
        pred = sess.run(tf.argmax(hyp_val, 1))
        print('step : ', step+1, '\nW:\n', np.round(W_val, 4), '\nb:', np.round(b_val, 4), "\ncost", cost_val,
             '\nhypothesis:\n', np.round(hyp_val, 4),'\npredicted:\n',pred)
        print('-'*20)
        sess.run(train, feed_dict={X:X_data, Y:Y_data})

step :  1 
W:
 [[1. 2.]
 [3. 4.]] 
b: [1. 2.] 
cost 8.000336 
hypothesis:
 [[3.000e-04 9.997e-01]] 
predicted:
 [1]
--------------------
step :  2 
W:
 [[1.2999 1.7001]
 [3.3999 3.6001]] 
b: [1.1 1.9] 
cost 2.8606791 
hypothesis:
 [[0.0572 0.9428]] 
predicted:
 [1]
--------------------
step :  3 
W:
 [[1.5827 1.4173]
 [3.777  3.223 ]] 
b: [1.1942 1.8058] 
cost 0.115447275 
hypothesis:
 [[0.891 0.109]] 
predicted:
 [0]
--------------------
step :  4 
W:
 [[1.6154 1.3846]
 [3.8206 3.1794]] 
b: [1.2051 1.7949] 
cost 0.06711332 
hypothesis:
 [[0.9351 0.0649]] 
predicted:
 [0]
--------------------
step :  5 
W:
 [[1.6349 1.3651]
 [3.8466 3.1534]] 
b: [1.2116 1.7884] 
cost 0.04834303 
hypothesis:
 [[0.9528 0.0472]] 
predicted:
 [0]
--------------------
step :  6 
W:
 [[1.6491 1.3509]
 [3.8654 3.1346]] 
b: [1.2164 1.7836] 
cost 0.038020182 
hypothesis:
 [[0.9627 0.0373]] 
predicted:
 [0]
--------------------
step :  7 
W:
 [[1.6603 1.3397]
 [3.8804 3.1196]] 
b: [1.2201 1.7799] 
cost 0.0314199